const SYSTEM_PROT = 9999;
const PROXY_WORKER = 'PROXY';
const SYSTEM_PROXY_START = 'SYSTEM_PROXY_START'
const SYSTEM_PROXY_CLOSE = 'SYSTEM_PROXY_CLOSE'
const SYSTEM_TIP_CRT = 'SYSTEM_TIP_CRT'
const SYSTEM_CLICK_BTN = 'SYSTEM_CLICK_BTN'
const CRT_INSTALL_SUCCESS = 'CRT_INSTALL_SUCCESS'
const CHILD_MSG_TO_MAIN = 'CHILD_MSG_TO_MAIN'
const CRT_INSTALL_NET_SUCCESS = 'CRT_INSTALL_NET_SUCCESS'
const SYSTEM_CLICK_NET_BTN = 'SYSTEM_CLICK_NET_BTN'
const SYSTEM_CLICK_NET_BTN_SUCCESS = 'SYSTEM_CLICK_NET_BTN_SUCCESS'

module.exports = {
  SYSTEM_PROT,
  PROXY_WORKER,
  SYSTEM_PROXY_START,
  SYSTEM_PROXY_CLOSE,
  SYSTEM_CLICK_BTN,
  SYSTEM_TIP_CRT,
  CRT_INSTALL_NET_SUCCESS,
  CHILD_MSG_TO_MAIN,
  CRT_INSTALL_SUCCESS,
  SYSTEM_CLICK_NET_BTN,
  SYSTEM_CLICK_NET_BTN_SUCCESS
}
