const SYSTEM_PROT = 56231;
const PROXY_WORKER = 'PROXY';
const SYSTEM_PROXY_START = 'SYSTEM_PROXY_START'
const SYSTEM_PROXY_CLOSE = 'SYSTEM_PROXY_CLOSE'

module.exports = {
  SYSTEM_PROT,
  PROXY_WORKER,
  SYSTEM_PROXY_START,
  SYSTEM_PROXY_CLOSE
}