const SYSTEM_PROT = 56231;
const PROXY_WORKER = 'PROXY';
const SYSTEM_PROXY_START = 'SYSTEM_PROXY_START'
const SYSTEM_PROXY_CLOSE = 'SYSTEM_PROXY_CLOSE'
const SYSTEM_TIP_CRT = 'SYSTEM_TIP_CRT'
const SYSTEM_CLICK_BTN = 'SYSTEM_CLICK_BTN'
const CRT_INSTALL_SUCCESS = 'CRT_INSTALL_SUCCESS'

module.exports = {
  SYSTEM_PROT,
  PROXY_WORKER,
  SYSTEM_PROXY_START,
  SYSTEM_PROXY_CLOSE,
  SYSTEM_CLICK_BTN,
  SYSTEM_TIP_CRT,
  CRT_INSTALL_SUCCESS
}
